//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Manager.Resources {
    using System;
    using System.Reflection;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_General {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_General() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Piranha.Manager.Resources.Localization.General", typeof(Localization_General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }

        internal static string Content_type {
            get {
                return ResourceManager.GetString("Content type", resourceCulture);
            }
        }

        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }

        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }

        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }

        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }

        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        internal static string Looks_like_there_s_no_items_here__Click_on_the_button_above_to_get_started_ {
            get {
                return ResourceManager.GetString("Looks like there\'s no items here. Click on the button above to get started!", resourceCulture);
            }
        }

        internal static string Looks_like_there_s_no_items_here__Click_on_the_button_below_to_get_started_ {
            get {
                return ResourceManager.GetString("Looks like there\'s no items here. Click on the button below to get started!", resourceCulture);
            }
        }

        internal static string Looks_like_there_s_no_items_here__Click_on_the_button_to_the_left_to_get_started_ {
            get {
                return ResourceManager.GetString("Looks like there\'s no items here. Click on the button to the left to get started!" +
                        "", resourceCulture);
            }
        }

        internal static string Main_content {
            get {
                return ResourceManager.GetString("Main content", resourceCulture);
            }
        }

        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }

        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        internal static string Open_public_URL_in_new_tab {
            get {
                return ResourceManager.GetString("Open public URL in new tab", resourceCulture);
            }
        }

        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }

        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }

        internal static string Publish_date {
            get {
                return ResourceManager.GetString("Publish date", resourceCulture);
            }
        }

        internal static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }

        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        internal static string Search___ {
            get {
                return ResourceManager.GetString("Search...", resourceCulture);
            }
        }

        internal static string Select_block {
            get {
                return ResourceManager.GetString("Select block", resourceCulture);
            }
        }

        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }

        internal static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }

        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }

        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }

        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        internal static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", resourceCulture);
            }
        }

        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }

        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
