//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Manager.Resources {
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Page {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Page() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Piranha.Manager.Resources.Localization.Pages", typeof(Localization_Page).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Add_page {
            get {
                return ResourceManager.GetString("Add page", resourceCulture);
            }
        }

        internal static string An_error_occured_while_deleting_the_page {
            get {
                return ResourceManager.GetString("An error occured while deleting the page", resourceCulture);
            }
        }

        internal static string Edit_page {
            get {
                return ResourceManager.GetString("Edit page", resourceCulture);
            }
        }

        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }

        internal static string If_the_page_should_be_hidden_in_the_sitemap {
            get {
                return ResourceManager.GetString("If the page should be hidden in the sitemap", resourceCulture);
            }
        }

        internal static string Meta_keywords {
            get {
                return ResourceManager.GetString("Meta keywords", resourceCulture);
            }
        }

        internal static string Meta_description {
            get {
                return ResourceManager.GetString("Meta description", resourceCulture);
            }
        }

        internal static string Navigation_title {
            get {
                return ResourceManager.GetString("Navigation title", resourceCulture);
            }
        }

        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }

        internal static string The_page_was_successfully_deleted {
            get {
                return ResourceManager.GetString("The page was successfully deleted", resourceCulture);
            }
        }

        internal static string The_page_was_successfully_published {
            get {
                return ResourceManager.GetString("The page was successfully published", resourceCulture);
            }
        }

        internal static string The_page_was_successfully_saved {
            get {
                return ResourceManager.GetString("The page was successfully saved", resourceCulture);
            }
        }

        internal static string The_page_was_successfully_reverted_to_its_previous_state {
            get {
                return ResourceManager.GetString("The page was successfully reverted to its previous state", resourceCulture);
            }
        }

        internal static string Welcome_to_your_new_page__Click_on_the_button_above_to_add_your_first_block_of_content_ {
            get {
                return ResourceManager.GetString("Welcome to your new page. Click on the button above to add your first block of co" +
                        "ntent!", resourceCulture);
            }
        }

        internal static string Your_page_title {
            get {
                return ResourceManager.GetString("Your page title", resourceCulture);
            }
        }
    }
}
