//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Manager.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_Media {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_Media() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Piranha.Manager.Resources.Localization.Media", typeof(Localization_Media).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Add_folder {
            get {
                return ResourceManager.GetString("Add folder", resourceCulture);
            }
        }
        
        internal static string Drop_files_here_or_click_to_upload_ {
            get {
                return ResourceManager.GetString("Drop files here or click to upload.", resourceCulture);
            }
        }
        
        internal static string Download_media {
            get {
                return ResourceManager.GetString("Download media", resourceCulture);
            }
        }
        
        internal static string Folder_name {
            get {
                return ResourceManager.GetString("Folder name", resourceCulture);
            }
        }
        
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        internal static string Media_preview_is_not_available {
            get {
                return ResourceManager.GetString("Media preview is not available", resourceCulture);
            }
        }
        
        internal static string Open_media_in_new_tab {
            get {
                return ResourceManager.GetString("Open media in new tab", resourceCulture);
            }
        }
        
        internal static string Select_media {
            get {
                return ResourceManager.GetString("Select media", resourceCulture);
            }
        }
        
        internal static string our_browser_does_not_support_the_video_tag_ {
            get {
                return ResourceManager.GetString("our browser does not support the video tag.", resourceCulture);
            }
        }
    }
}
