<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Piranha\Piranha.csproj" />
  </ItemGroup>

</Project>
