name: .NET Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: |
        mkdir -p coverage
        dotnet test test/Piranha.Tests/Piranha.Tests.csproj \
          -f net10.0 --no-build -s build/tests.runsettings --verbosity normal \
          -p:CollectCoverage=true \
          -p:CoverletOutputFormat=json \
          -p:CoverletOutput=../../coverage/coverage
        dotnet test test/Piranha.Manager.Tests/Piranha.Manager.Tests.csproj \
          -f net10.0 --no-build -s build/tests.runsettings --verbosity normal \
          -p:CollectCoverage=true \
          -p:CoverletOutputFormat=lcov \
          -p:MergeWith=../../coverage/coverage.net10.0.json \
          -p:CoverletOutput=../../coverage/lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.net10.0.info
